MusicWebsite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^music/', include("music.urls"))
]

if settings.DEBUG :
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

music/urls.py
from django.conf.urls import url
from . import views

app_name = 'music'

urlpatterns = [
    # /music/
    url(r'^$', views.index , name="index") ,

    # /music/45/
    url(r'^(?P<album_id>[0-9]+)/$' , views.detail , name="detail") ,

    # /music/45/favourite/
    url(r'^(?P<album_id>[0-9]+)/favourite/$', views.favourite, name="favourite")
]

music/models.py
from django.db import models

# Create your models here.


# let album Red has Primary key 1
class Album(models.Model) :
    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=500)
    genre = models.CharField(max_length=100)
    album_logo = models.FileField()

    def __str__(self):
        return self.artist + '_' + self.album_title

class Song(models.Model) :
    album = models.ForeignKey(Album , on_delete=models.CASCADE)
    file_type = models.CharField(max_length=10)
    song_title = models.CharField(max_length=250)
    is_favourite = models.BooleanField(default=False)

    def __str__(self):
        return self.song_title

music/views.py
from django.http import HttpResponse
from django.http import Http404
from .models import Album , Song
from django.template import loader
from django.shortcuts import render , get_object_or_404

# Create your views here.

'''
def index(request) :
    all_albums = Album.objects.all()
    html = ""
    for f in all_albums :
        url = "/music/" + str(f.id) + "/"
        html += '<a href="'+url+'" > ' + f.album_title + "</a><br>"

    return HttpResponse(html)
'''

            # OR

'''
def index(request) :
    all_albums = Album.objects.all()
    template = loader.get_template("music/index.html")
    # Create a dictionary ..
    context = {"all_albums" : all_albums}
    return HttpResponse(template.render(context,request))
'''

            # OR

def index(request) :
    all_albums = Album.objects.all()
    # Create a dictionary ..
    context = {"all_albums" : all_albums}
    return render(request , "music/index.html" , context)

'''

def detail(request , album_id) :
    try :
        album = Album.objects.get(pk=album_id)
        album_title = album.album_title
        album_logo = album.album_logo
        all_songs = album.song_set.all()
        context = {"all_songs": all_songs , "album_title" : album_title , "album_logo" : album_logo}
    except Album.DoesNotExist :
        raise Http404("Album does not exist")
    return render(request , "music/detail.html" , context)
'''

                    # OR

def detail(request , album_id) :
    album = get_object_or_404(Album , pk=album_id)
    album_title = album.album_title
    album_logo = album.album_logo
    all_songs = album.song_set.all()
    context = {"all_songs": all_songs , 'album': album , "album_title" : album_title , "album_logo" : album_logo}
    return render(request , "music/detail.html" , context)

def favourite(request , album_id) :
    album = get_object_or_404(Album , pk=album_id)
    album_title = album.album_title
    album_logo = album.album_logo
    all_songs = album.song_set.all()
    try:
        selected_song = album.song_set.get(pk=request.POST['song'])
    except (KeyError , Song.DoesNotExist) :
        return render(request , "music/detail.html", {
            'album' : album ,
            'error_message' : "You did not selected any song" ,
        })
    else:
        selected_song.is_favourite = True
        selected_song.save()
        return render(request, "music/detail.html", {"all_songs": all_songs , 'album': album , "album_title" : album_title , "album_logo" : album_logo})

music/templates/music/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Details</title>
    <style>
        table {
    border-collapse: collapse;
    width: 100%;
}

th, td {
    text-align: left;
    padding: 8px;
}

tr:nth-child(even){background-color: #f2f2f2}

th {
    background-color: #4CAF50;
    color: white;
}
    </style>
</head>
<body>

    <img src="{{ album_logo.url }}" height="250" width="250">

    {% if error_message %}
        <p>{{ error_message }}</p>
    {% endif %}

    {% if all_songs %}

    <h1>Songs present in {{ album_title }} </h1>

    <form action="{% url 'music:favourite' album.id %}" method="post">

    {% csrf_token %}

    <table>
        <tr>
        <th>Choose</th>
        <th>Favourite</th>
        <th>ID</th>
        <th>Title</th>
        <th>File Type</th>
        </tr>

        {% for songs in all_songs %}
        <tr>
        <td><input type="radio" name="song" value="{{ songs.id }}"></td>
        {% if songs.is_favourite %}
            <td>YES</td>
        {% else %}
            <td>NO</td>
        {% endif %}
        <td>{{ songs.id }}</td>
        <td>{{ songs.song_title }}</td>
        <td>{{ songs.file_type }}</td>
    </tr>
    {% endfor %}

    </table>

    <input type="submit" value="Favourite" >

    </form>

    {% else %}
    <h2>No Songs Present</h2>
    {% endif %}

</body>
</html>

music/templates/music/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Music Homepage</title>
</head>
<body>
<h3>Here are all my Albums</h3>

{% if all_albums %}
    <ul>
        {% for album in all_albums %}
        <!-- <li><a href="/music/{{ album.id }}">{{ album.album_title }}</a></li> -->
            <!-- OR -->
        <li><a href="{% url 'detail' album.id %}">{{ album.album_title }}</a></li>
        {% endfor %}
    </ul>
{% else %}
    <h3>You dont have any album</h3>
{% endif %}
</body>
</html>